### ISSUE TITLE
Clarification about cutadapt config

### ISSUE THREAD

**Issue by Ax3man** [akcorut/kGWASflow#16]
Hi Kivanc,

I have a question about the configuration of the adapter trimming part of the pipeline. It's not clear to me from the documentation on the config how to provide the adapter sequences for paired-end reads.

Here's the relevant config block:
```
  # ----------------------------------------------------------------------
  #     cutadapt Params
  # ----------------------------------------------------------------------
  cutadapt:
    # Number of threads for cutadapt
    threads: 8

    # See cutadapt manual:
    # https://cutadapt.readthedocs.io/en/stable/guide.html
    # Set params for single end files
    se:
      adapters: ""
      extra: ""
    # Set params for paired end files
    # https://cutadapt.readthedocs.io/en/stable/guide.html
    pe:
      adapters: ""
      extra: ""
```

Reading the cutadapt docs makes it clear both an `-a` and `-A` argument should be provided with the two adapters. Should I be providing these flags like so?

```
    pe:
      adapters: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
      extra: ""
```

Thanks so much for your help.
